### ISSUE TITLE
Line 18: Model selection: grid search

### ISSUE THREAD

**Issue by nujcharee** [pablosuau/machine_learning#1]
I downloaded the codes to run locally and this line seems to hang... any suggestions please? Thanks so much.

**Comment by nujcharee** [comment]
Hi there, 
I basically download your repository as zip file and unzip it, I havent changed any structure or anything. I got python 3.6 on my machine and I run jupyter notebook :) Thanks Pablo.

Its basically hangs there - I am not that familiar with python so it might be my mistake. Thank you so much Pablo.

**Comment by pablosuau** [comment]
Hi,
I am also using Python 3.6 (3.6.4 specifically) and Jupyter Notebooks served through Anaconda Navigator. 

Have you tried interrupting the execution of the code to see where it got stuck? (Ctrl+C)

**Comment by nujcharee** [comment]
Hi there, so I upgrade my scikit-learn library.... this time I go as far as 
`y_pred = pip_clf.predict(X_test)`

then I got this error message  raise 
```
NotFittedError(msg % {'name': type(estimator).__name__})
NotFittedError: CountVectorizer - Vocabulary wasn't fitted.
```
I use python 3.6 too and also use Anaconda on virtual env. 
Thanks so much Pablo :)

**Comment by pablosuau** [comment]
Did you update to the latest version? I may need to do so as well to test the error. What version of scikit-learn are you using?

**Comment by nujcharee** [comment]
Hi there
I used the latest version yes.

I tested it by running on MAC and i didn't have any error at all. I bet the virtual env on my windows just got something incompatible maybe. Apologies to waste your time Pablo. All good now :)
